FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

ENV PIP_NO_CACHE_DIR=1

COPY api/requirements-api.txt ./api/requirements-api.txt
COPY api/requirements-runtime.txt ./api/requirements-runtime.txt
RUN pip install -r api/requirements-api.txt

COPY api ./api

CMD uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-5001}
