"""Request identity for rate limiting: user > device fingerprint > client IP.

On a campus network hundreds of legitimate users share one NAT'd IP, so IP is
the identity of last resort. Authenticated users are limited per account; an
anonymous browser that sends the ``X-Client-Id`` header (a random UUID plus a
hash of coarse device signals, generated by ``web/lib/client-id.ts``) is
limited per device.
"""
from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass

from fastapi import Request

CLIENT_ID_HEADER = "X-Client-Id"
CLIENT_TZ_HEADER = "X-Client-Tz"

# `${crypto.randomUUID()}.${fnv1a-hash8}` — anything else is ignored so an
# attacker cannot mint unlimited buckets by stuffing garbage in the header.
_CLIENT_ID_RE = re.compile(r"^[0-9a-fA-F-]{36}(\.[0-9a-f]{8})?$")


@dataclass(frozen=True)
class Identity:
    kind: str  # "user" | "fp" | "ip"
    key: str  # e.g. "user:<uuid>", "fp:<hash>", "ip:<addr>"

    @property
    def blockable(self) -> bool:
        """Temp blocks never apply to bare IPs — that would lock a whole NAT."""
        return self.kind in {"user", "fp"}


def fingerprint_from_header(value: str | None) -> str | None:
    """Validated, hashed device identifier, or None."""
    if not value or not _CLIENT_ID_RE.match(value.strip()):
        return None
    return hashlib.sha256(value.strip().lower().encode()).hexdigest()[:16]


def client_ip(request: Request, *, trusted_proxy_hops: int = 0) -> str:
    """Best-effort client address.

    With ``trusted_proxy_hops == 0`` the socket peer is authoritative (uvicorn
    already rewrites it from X-Forwarded-For only for peers in
    FORWARDED_ALLOW_IPS). With N trusted proxies in front, the client is the
    Nth-from-the-right X-Forwarded-For entry; the left of the list is
    client-controlled and must never be trusted.
    """
    if trusted_proxy_hops > 0:
        forwarded = request.headers.get("x-forwarded-for", "")
        parts = [p.strip() for p in forwarded.split(",") if p.strip()]
        if len(parts) >= trusted_proxy_hops:
            return parts[-trusted_proxy_hops]
    return request.client.host if request.client else "unknown"


def identify(
    request: Request,
    *,
    user_id: str | None = None,
    trusted_proxy_hops: int = 0,
) -> Identity:
    """Most-specific available identity for this request."""
    if user_id:
        return Identity("user", f"user:{user_id}")
    fp = fingerprint_from_header(request.headers.get(CLIENT_ID_HEADER))
    if fp:
        return Identity("fp", f"fp:{fp}")
    return Identity("ip", f"ip:{client_ip(request, trusted_proxy_hops=trusted_proxy_hops)}")
