"""Image and audio generation nodes.

Generated bytes are uploaded to Supabase Storage and the node returns the
public URL. Inlining them as base64 ``data:`` URLs (the original v1 behaviour)
silently broke the editor: a single image is far past the ~256 KB Supabase
Realtime message limit, so the ``node_succeeded`` broadcast carrying it was
rejected and the canvas never rendered anything.
"""
from __future__ import annotations

import base64
from typing import Any

from ...providers import get_provider
from ...storage import upload_media
from ..context import ExecutionContext
from .inputs import merge_inputs
from .integrations import apply_integration_options


# Below this size a base64 data URL still fits inside a Realtime message
# (base64 inflates by 4/3), so it stays usable as a fallback when Storage is
# not configured — e.g. local dev without Supabase credentials.
_INLINE_FALLBACK_MAX_BYTES = 180_000


# Image / audio model label maps.
IMAGE_MODEL_TO_PROVIDER: dict[str, str] = {
    "GPT Image 1": "openai",
    # DALL-E is retired upstream; the provider remaps these onto gpt-image-1 so
    # flows saved with the old dropdown label keep running.
    "DALLE 3": "openai",
    "DALL-E 3": "openai",
    "DreamShaper": "cloudflare",
    "Flux Schnell": "cloudflare",
    "Midjourney": "cloudflare",
}
AUDIO_MODEL_TO_PROVIDER: dict[str, str] = {
    "TTS-1": "openai",
    "Aura 2 (Cloudflare)": "cloudflare",
}


async def execute(node: dict, inputs: list[Any], ctx: ExecutionContext) -> str:
    data = node.get("data", {}) or {}
    options: dict[str, Any] = dict(data.get("options") or {})
    options.setdefault("voice", data.get("voice"))
    options.setdefault("speed", data.get("speed"))
    options.setdefault("negativePrompt", data.get("negativePrompt"))
    if data.get("prompt") is not None:
        options.setdefault("prompt", data.get("prompt"))
    if data.get("model") is not None:
        options.setdefault("model", data.get("model"))
    options = await apply_integration_options(data, ctx, options)

    node_type = node.get("type")
    label = data.get("model") or ("GPT Image 1" if node_type == "imagegen" else "TTS-1")
    if node_type == "imagegen":
        provider_name = IMAGE_MODEL_TO_PROVIDER.get(label, "cloudflare")
        output_type = "image"
    else:
        provider_name = AUDIO_MODEL_TO_PROVIDER.get(label, "openai")
        output_type = "audio"

    provider = get_provider(provider_name)
    if provider is None:
        raise ValueError(f"Unknown provider: {provider_name}")

    input_value = merge_inputs(inputs)
    if input_value is None:
        input_value = data.get("prompt") or ""
    result = await provider.generate(
        input=input_value,
        input_type="text",
        output_type=output_type,
        options=options,
    )
    if result.text:
        return result.text
    if result.blob is not None:
        return await _store(result.blob, result.mime, ctx, node)
    return ""


async def _store(blob: bytes, mime: str | None, ctx: ExecutionContext, node: dict) -> str:
    """Persist generated bytes and return a URL the editor can render."""
    node_id = str(node.get("id") or "node")
    try:
        return await upload_media(blob, mime, run_id=ctx.run_id, node_id=node_id)
    except Exception as exc:
        if len(blob) <= _INLINE_FALLBACK_MAX_BYTES:
            b64 = base64.b64encode(blob).decode("ascii")
            return f"data:{mime};base64,{b64}"
        raise RuntimeError(
            f"Generated {len(blob)} bytes of media but could not store it, and "
            "it is too large to inline (the editor would silently drop it). "
            f"Storage error: {exc}"
        ) from exc
